/**
 * Action proposal type definitions
 *
 * Proposals represent AI-generated action suggestions that must be
 * evaluated against policies and optionally approved by users.
 */

import type {
  UUID,
  ISO8601String,
  OperationType,
  DataDomain,
  DataClassification,
  RollbackType,
  RollbackPlan,
  EntityReference,
  SkillReference,
  RiskLevel,
} from '../common';
import type { PolicyResult } from './policy';

/**
 * Complete action proposal
 *
 * Generated by the AI assistant when it wants to perform an action.
 * Must be evaluated by the policy engine before execution.
 */
export interface ActionProposal {
  /** Unique identifier */
  id: UUID;
  /** When proposal was created */
  timestamp: ISO8601String;
  /** Natural language description of what the AI wants to do */
  intent: string;
  /** ServiceNow operation type */
  operation: OperationType;
  /** Target entity (if applicable) */
  target_entity: EntityReference | null;
  /** Which ServiceNow instance to use */
  data_domain: DataDomain;
  /** Sensitivity classification of data involved */
  data_classification: DataClassification;
  /** How well this action can be reversed */
  reversibility: RollbackType;
  /** AI confidence score (0-1) */
  confidence: number;
  /** Skills that contributed to this proposal */
  related_skills: SkillReference[];
  /** Plan for rolling back if needed */
  rollback_plan: RollbackPlan | null;
  /** Model that generated this proposal */
  evaluation_model: string;
  /** Original user input that triggered this */
  raw_user_input: string;
  /** Whether user must approve before execution */
  requires_confirmation: boolean;
  /** Risk assessment */
  risk_level: RiskLevel;
  /** Result of policy evaluation (set after evaluation) */
  policy_result?: PolicyResult;
  /** User's decision (approve/deny) if confirmation required */
  user_decision?: 'approved' | 'denied';
  /** When action was executed (if executed) */
  executed_at?: ISO8601String;
  /** Execution result details */
  execution_result?: ExecutionResult;
}

/**
 * Result of executing an action proposal
 */
export interface ExecutionResult {
  /** Whether execution succeeded */
  success: boolean;
  /** Duration in milliseconds */
  duration_ms: number;
  /** Error message (if failed) */
  error?: string;
  /** Output data from the operation */
  output?: Record<string, unknown>;
  /** Entity that was created/modified (if applicable) */
  affected_entity?: EntityReference;
}

/**
 * Proposal creation input (AI generates this)
 */
export type ProposalCreate = Omit<
  ActionProposal,
  'id' | 'timestamp' | 'policy_result' | 'user_decision' | 'executed_at' | 'execution_result'
>;

/**
 * Proposal approval/denial
 */
export interface ProposalDecision {
  /** Proposal being decided on */
  proposal_id: UUID;
  /** User's decision */
  decision: 'approved' | 'denied';
  /** Optional feedback from user */
  feedback?: string;
  /** Timestamp of decision */
  decided_at: ISO8601String;
}
