disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - .build
  - Tests

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length: 1
  max_length: 60

type_name:
  min_length: 3
  max_length: 60
