/**
 * JSON Schema for ActionProposal
 *
 * Used for constrained JSON decoding with Ollama.
 * This schema ensures the LLM generates valid ActionProposal objects.
 */

/**
 * ActionProposal JSON Schema for Ollama constrained decoding
 *
 * Note: This schema omits fields that are auto-generated:
 * - id (generated via crypto.randomUUID())
 * - timestamp (generated via new Date().toISOString())
 * - evaluation_model (set by service)
 * - raw_user_input (preserved from input)
 * - related_skills (populated by policy engine)
 * - rollback_plan (generated by expert AI if needed)
 */
export const ACTION_PROPOSAL_SCHEMA = {
  type: 'object',
  required: [
    'intent',
    'operation',
    'data_domain',
    'data_classification',
    'reversibility',
    'confidence',
    'requires_confirmation',
    'risk_level',
  ],
  properties: {
    intent: {
      type: 'string',
      description:
        'Natural language description of what the AI wants to do (e.g., "Create a high-priority ticket for server downtime")',
      minLength: 5,
      maxLength: 500,
    },
    operation: {
      type: 'string',
      description:
        'Operation type in format "module:action" (e.g., "incident:create", "calendar:read")',
      pattern: '^[a-z_]+:[a-z_]+$',
      examples: ['incident:create', 'calendar:create', 'task:update', 'note:delete', 'file:read'],
    },
    target_entity: {
      oneOf: [
        { type: 'null' },
        {
          type: 'object',
          required: ['type', 'id', 'source'],
          properties: {
            type: {
              type: 'string',
              description: 'Entity type (e.g., "incident", "calendar_event", "task")',
            },
            id: {
              type: 'string',
              description: 'Entity ID or sys_id',
            },
            source: {
              type: 'string',
              description: 'Source system or instance',
            },
          },
        },
      ],
      description: 'Target entity for the operation (null for new entities)',
    },
    data_domain: {
      type: 'string',
      enum: ['enterprise', 'personal'],
      description: 'Data domain: "enterprise" for work-related, "personal" for individual tasks',
    },
    data_classification: {
      type: 'string',
      enum: ['public', 'internal', 'confidential', 'restricted'],
      description:
        'Sensitivity classification: "public" (no sensitive data), "internal" (company info), "confidential" (restricted access), "restricted" (highly sensitive)',
    },
    reversibility: {
      type: 'string',
      enum: ['FULL', 'PARTIAL', 'COMPENSATABLE', 'IRREVERSIBLE'],
      description:
        'Rollback capability: "FULL" (easily undone), "PARTIAL" (some parts undoable), "COMPENSATABLE" (can be compensated), "IRREVERSIBLE" (cannot undo)',
    },
    confidence: {
      type: 'number',
      minimum: 0,
      maximum: 1,
      description:
        'AI confidence score (0.0-1.0). Use 0.9+ for clear intent, 0.5-0.8 for ambiguous, <0.5 for unclear.',
    },
    requires_confirmation: {
      type: 'boolean',
      description:
        'Whether user must approve before execution (true for write/delete, false for reads)',
    },
    risk_level: {
      type: 'string',
      enum: ['low', 'medium', 'high'],
      description:
        'Risk assessment: "low" (reads, views), "medium" (updates, creates), "high" (deletes, bulk operations)',
    },
  },
  additionalProperties: false,
} as const;
